### ISSUE TITLE
 No such file or directory: '/content/musika/checkpoints/misc/opt_disc.npy'

### ISSUE THREAD

**Issue by frncscp** [marcoppasini/musika#34]
I'm trying to use the jupyter notebook to fine-tune the misc model, but apparently there is some code missing that is needed to do the re-training.

`Traceback (most recent call last):
  File "/content/musika/musika/musika_train.py", line 23, in <module>
    models_ls = M.initialize_networks()
  File "/content/musika/musika/models.py", line 760, in initialize_networks
    (critic, gen, enc, dec, enc2, dec2, gen_ema, [opt_dec, opt_disc], switch) = self.get_networks()
  File "/content/musika/musika/models.py", line 739, in get_networks
    ) = self.load(self.args.load_path, load_dec=False)
  File "/content/musika/musika/models.py", line 669, in load
    opt_disc.set_weights(np.load(path + "/opt_disc.npy", allow_pickle=True))
  File "/usr/local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/content/musika/checkpoints/misc/opt_disc.npy'`

**Comment by marcoppasini** [comment]
Does this happen when you run the finetuning notebook in Colab (https://colab.research.google.com/drive/1PowSw3doBURwLE-OTCiWkO8HVbS5paRb)?

**Comment by frncscp** [comment]
When I ran it yesterday it didn't, but now it does, weird, but thanks.
