### ISSUE TITLE
Encode audio files

### ISSUE THREAD

**Issue by mezaga** [marcoppasini/musika#37]
While trying to generate my dataset encodings, I keep getting an empty folder and the following message (Both in Colab and M1 Mac):

`too many indices for array: array is 1-dimensional, but 2 were indexed
Exception ignored! Continuing..  `

**Comment by dr-zaib** [comment]
helloo!
i am actually having the same problem and trying to figure it out, any news?

**Comment by marcoppasini** [comment]
Are you using stereo audio files? If you are using mono files, try to convert them to stereo and try to encode again, I think it should solve the issue :-)

**Comment by dr-zaib** [comment]
helloo
it definitely was an error about the audio channelling (stereo/mono/transformation into an array/back trasforming to an audio file..stuff!) after an audio data augmentation i did to my dataset! 

for anyone having the same problem I recommend to check this, it may be really uselful, since the encoder makes uses of Audiosegment from pydub library

https://github.com/jiaaro/pydub/blob/master/API.markdown#audiosegmentexport

**Comment by dr-zaib** [comment]
But when running the encoder today from the colab script (since we are talking about the Encoding part here) i got this error i really do not know how to debug and/or fix, any hint/solution ? 


Traceback (most recent call last):
  File "/content/musika/musika_encode.py", line 7, in <module>
    from utils_encode import UtilsEncode_functions
  File "/content/musika/utils_encode.py", line 9, in <module>
    from utils import Utils_functions
  File "/content/musika/utils.py", line 11, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.9/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.9/site-packages/gradio/components.py", line 38, in <module>
    from gradio import media_data, processing_utils, utils
  File "/usr/local/lib/python3.9/site-packages/gradio/processing_utils.py", line 17, in <module>
    from gradio import encryptor, utils
  File "/usr/local/lib/python3.9/site-packages/gradio/utils.py", line 395, in <module>
    class Request:
  File "/usr/local/lib/python3.9/site-packages/gradio/utils.py", line 415, in Request
    client = httpx.AsyncClient()
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: __init__() got an unexpected keyword argument 'socket_options'
